### PR TITLE
check if msgpool is empty by using isEmpty method instead of size

### PR DESCRIPTION
**Pull request by dinal**
ConcurrentLinkedQueue.size() is in O(n)
ConcurrentLinkedQueue,isEmpty() is in O(1)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-jxio/145/ for details (Mellanox internal link).

**Comment by orshalev** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-jxio/146/ for details (Mellanox internal link).

**Comment by orshalev** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test SUCCESS.
See http://hpc-master.lab.mtl.com:8080/job/accl-jxio/153/ for details (Mellanox internal link).

**Pull request merged**
