### PR TITLE
getMsg fix for NullPointerException

### PR DESCRIPTION
**Pull request by bivas**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by mellanox-github** [comment]
Test SUCCESS.
See http://hpc-master.lab.mtl.com:8080/job/accl-jxio/155/ for details (Mellanox internal link).

**Comment by rafiw** [comment]
Hi
please rebase the branch and remove commit "Merge branch 'master' of github.com:accelio/JXIO"
and create two pull request since the patches are not related

**Comment by bivas** [comment]
@rafiw  opened 2 PRs instead of this one:
PR #27 
and
PR #28

**Pull request closed without merging**
