### PR TITLE
use external settings for output folders

### PR DESCRIPTION
**Pull request by bivas**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by Di0gen** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-jxio-pr/1/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-jxio-pr/2/ for details (Mellanox internal link).

**Pull request merged**
